# Generated by Django 3.2.8 on 2021-11-04 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=2000)),
                ('puntaje_limite', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bloqueado', models.BooleanField(default=False)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('imagen_modojuego', models.FileField(db_column='imagen_modojuego', null=True, upload_to='juego/recursos')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modo_juego', to='juego.juego')),
                ('puntaje_maximo_jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modo_jugador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(unique=True)),
                ('codigo_nivel', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=5000)),
                ('imagen_nivel', models.FileField(db_column='imagen_nivel', null=True, upload_to='juego/recursos')),
                ('imagen_juego', models.FileField(db_column='imagen_juego', null=True, upload_to='juego/recursos')),
                ('modo_juego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='juego.modojuego')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField()),
                ('pregunta', models.CharField(max_length=5000)),
                ('puntos_correcto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('puntos_incorrecto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('respuesta', models.CharField(max_length=1000)),
                ('ayuda', models.CharField(max_length=1000, null=True)),
                ('imagen_pregunta', models.FileField(db_column='imagen_nivel', null=True, upload_to='juego/recursos')),
                ('imagen_juego', models.FileField(db_column='imagen_juego', null=True, upload_to='juego/recursos')),
                ('modo_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modo_juego_pregunta', to='juego.modojuego')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opcion', models.CharField(max_length=1000)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_opcion', to='juego.pregunta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
