# Generated by Django 3.2.8 on 2021-11-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.FileField(db_column='imagen_juego', null=True, upload_to='juego/recursos'),
        ),
        migrations.AddField(
            model_name='juego',
            name='miniatura',
            field=models.FileField(db_column='imagen_juego_miniatura', null=True, upload_to='juego/recursos'),
        ),
    ]
