# Generated by Django 3.2.8 on 2021-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_modojuego_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modojuego',
            name='color',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
