# Generated by Django 3.2.8 on 2021-11-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_logro'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='categoria',
            field=models.PositiveBigIntegerField(choices=[(1, 'puntos diarios'), (2, 'inicio consecutivo'), (3, 'respuestas consecutivas'), (4, 'ayuda solicitada')], default=1),
        ),
    ]
