# Generated by Django 3.2.8 on 2021-11-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0008_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canjeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.FileField(db_column='imagen_canjeo', null=True, upload_to='juego/recursos')),
                ('miniatura', models.FileField(db_column='imagen_canjeo_miniatura', null=True, upload_to='juego/recursos')),
                ('categoria', models.PositiveBigIntegerField(choices=[(1, 'Alimentos'), (2, 'Productos'), (3, 'Servicios'), (4, 'Tickets')], default=1)),
                ('puntos_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoCanjeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.FileField(db_column='imagen_producto_canjeo', null=True, upload_to='juego/recursos')),
                ('miniatura', models.FileField(db_column='imagen_producto_canjeo_miniatura', null=True, upload_to='juego/recursos')),
                ('puntos_necesarios', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('canjeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_canjeo_canjeo', to='juego.canjeo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
