# Generated by Django 3.2.8 on 2021-11-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0009_canjeo_productocanjeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='enlace_juego',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
