# Generated by Django 3.2.8 on 2021-11-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0010_juego_enlace_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.FileField(db_column='imagen_canjeo', null=True, upload_to='juego/recursos')),
                ('miniatura', models.FileField(db_column='imagen_canjeo_miniatura', null=True, upload_to='juego/recursos')),
                ('categoria', models.PositiveBigIntegerField(choices=[(1, 'puntos diarios'), (2, 'inicio consecutivo'), (3, 'respuestas consecutivas'), (4, 'ayuda solicitada')], default=1)),
                ('puntos_requeridos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
