# Generated by Django 3.2.8 on 2021-11-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0014_auto_20211114_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriapuzzle',
            name='puntaje_maximo',
        ),
    ]
