# Generated by Django 3.2.8 on 2021-10-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
