# Generated by Django 3.2.8 on 2021-11-10 15:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_cantidad_ayuda_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='logros',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logros_temporal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], null=True, size=None),
        ),
    ]
