# Generated by Django 3.2.8 on 2021-11-10 23:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20211110_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='productos_canjeados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
